import { TiwaniEvent } from "../types/event";
import { DuesPeriod, LedgerEntry } from "../types/finance";
import { Listing } from "../types/marketplace";
import { LibraryDocument } from "../types/library";
import { TiwaniNotification } from "../types/notification";
import { Election, Poll } from "../types/voting";
import { JoinRequest, User } from "../types/user";

export const mockUsers: User[] = [
  {
    uid: "admin-1",
    fullName: "Chukwuemeka Obi",
    email: "admin@tiwani.app",
    phone: "08034567890",
    photoURL: null,
    role: "admin",
    status: "active",
    financialStatus: "green",
    outstandingBalance: 0,
    address: "12 Association Close, Lagos",
    maritalStatus: "married",
    dateOfBirth: "1984-04-12",
    spouseName: "Adaeze Obi",
    spouseDateOfBirth: "1987-11-03",
    weddingAnniversary: "2012-08-18",
    children: [{ name: "Chidera Obi", dateOfBirth: "2016-03-12" }],
    memberSince: "2021-02-01",
    notificationPreferences: { events: true, finance: true, voting: true },
    currencySymbol: "₦",
    timezone: "WAT",
  },
  {
    uid: "member-1",
    fullName: "Tiwalade Adebayo",
    email: "member@tiwani.app",
    phone: "08098765432",
    photoURL: null,
    role: "member",
    status: "active",
    financialStatus: "red",
    outstandingBalance: 15000,
    address: "8 Unity Avenue, Ikeja",
    maritalStatus: "single",
    dateOfBirth: "1991-09-22",
    spouseName: null,
    spouseDateOfBirth: null,
    weddingAnniversary: null,
    children: [],
    memberSince: "2023-06-10",
    notificationPreferences: { events: true, finance: true, voting: false },
    currencySymbol: "₦",
    timezone: "WAT",
  },
  {
    uid: "chair-1",
    fullName: "Nkiru Okafor",
    email: "chair@tiwani.app",
    phone: "08123456789",
    photoURL: null,
    role: "electoral_chairman",
    status: "active",
    financialStatus: "green",
    outstandingBalance: 0,
    address: "4 Palm Grove, Lekki",
    maritalStatus: "widowed",
    dateOfBirth: "1978-01-18",
    spouseName: null,
    spouseDateOfBirth: null,
    weddingAnniversary: null,
    children: [{ name: "Kamsi Okafor", dateOfBirth: "2009-07-09" }],
    memberSince: "2020-01-15",
    notificationPreferences: { events: true, finance: true, voting: true },
    currencySymbol: "₦",
    timezone: "WAT",
  },
];

export const mockJoinRequests: JoinRequest[] = [
  {
    id: "join-1",
    fullName: "Amaka Eze",
    email: "amaka@example.com",
    phone: "08022223333",
    message: "I would like to join and participate in community activities.",
    status: "pending",
    createdAt: new Date("2026-05-08T11:00:00+01:00"),
    reviewedAt: null,
    reviewedBy: null,
  },
];

export const mockEvents: TiwaniEvent[] = [
  {
    id: "event-1",
    title: "Annual General Meeting",
    description:
      "Monthly meeting to review dues, upcoming activities, committee reports, and member welfare updates.",
    category: "meeting",
    dateTime: new Date("2026-05-29T10:00:00+01:00"),
    location: "Eko Hotel, Lagos",
    createdBy: "admin-1",
    status: "published",
    rsvpList: ["admin-1", "chair-1", "member-1"],
    rsvpCount: 3,
    capacity: 30,
    attendees: [],
  },
  {
    id: "event-2",
    title: "Charity Walk & Drive",
    description:
      "Volunteer walk and supplies handoff for the local family support programme.",
    category: "volunteer",
    dateTime: new Date("2026-05-31T09:30:00+01:00"),
    location: "National Stadium, Surulere",
    createdBy: "admin-1",
    status: "published",
    rsvpList: ["member-1", "chair-1"],
    rsvpCount: 2,
    capacity: 50,
    attendees: ["member-1"],
  },
  {
    id: "event-3",
    title: "Christmas Gala Dinner",
    description:
      "End-of-year dinner with awards, family photos, music, and association announcements.",
    category: "social",
    dateTime: new Date("2026-12-20T19:00:00+01:00"),
    location: "Transcorp Hilton, Abuja",
    createdBy: "admin-1",
    status: "published",
    rsvpList: ["admin-1", "member-1", "chair-1"],
    rsvpCount: 3,
    capacity: 40,
    attendees: [],
  },
  {
    id: "event-4",
    title: "Finance Committee",
    description:
      "Committee review for dues collections, budgets, and pending member ledger updates.",
    category: "committee",
    dateTime: new Date("2026-06-02T18:00:00+01:00"),
    location: "Zoom (Virtual)",
    createdBy: "admin-1",
    status: "published",
    rsvpList: ["admin-1"],
    rsvpCount: 1,
    capacity: 8,
    attendees: [],
  },
];

export const mockPolls: Poll[] = [
  {
    id: "poll-1",
    title: "Meeting Format",
    question: "How should we host next quarter meetings?",
    status: "open",
    totalVotes: 18,
    resultVisibility: "after_vote",
    options: [
      {
        id: "physical",
        label: "Physical meetings",
        imageURL: null,
        voteCount: 10,
      },
      { id: "hybrid", label: "Hybrid meetings", imageURL: null, voteCount: 8 },
    ],
  },
];

export const mockElections: Election[] = [
  {
    id: "election-1",
    title: "2026 Executive Election",
    ballotType: "secret",
    status: "open",
    resultVisibility: "after_close",
    races: [
      {
        raceId: "president",
        office: "President",
        candidates: [
          {
            uid: "admin-1",
            name: "Chukwuemeka Obi",
            manifestoLine: "Transparent dues and stronger committees.",
            photoURL: null,
          },
          {
            uid: "chair-1",
            name: "Nkiru Okafor",
            manifestoLine: "Fair process and member-first governance.",
            photoURL: null,
          },
        ],
      },
    ],
  },
];

export const mockLedger: LedgerEntry[] = [
  {
    id: "ledger-1",
    uid: "member-1",
    type: "dues",
    label: "Q2 2026 Dues",
    amount: 15000,
    dueDate: new Date("2026-06-30"),
    paid: false,
    paidAt: null,
    note: "",
  },
  {
    id: "ledger-2",
    uid: "admin-1",
    type: "dues",
    label: "Q2 2026 Dues",
    amount: 15000,
    dueDate: new Date("2026-06-30"),
    paid: true,
    paidAt: new Date("2026-05-01"),
    note: "",
  },
  {
    id: "ledger-3",
    uid: "chair-1",
    type: "payment",
    label: "Bank transfer",
    amount: 15000,
    dueDate: null,
    paid: true,
    paidAt: new Date("2026-05-02"),
    note: "Q2 payment",
  },
];

export const mockDuesPeriods: DuesPeriod[] = [
  {
    id: "dues-1",
    name: "Q2 2026 Dues",
    amount: 15000,
    dueDate: new Date("2026-06-30"),
    status: "active",
    totalMembers: 3,
    paidCount: 2,
  },
];

export const mockNotifications: TiwaniNotification[] = [
  {
    id: "notif-1",
    type: "event",
    title: "Meeting reminder",
    body: "May General Meeting is this weekend.",
    sentAt: new Date("2026-05-12T09:00:00+01:00"),
    target: { route: "event_detail", eventId: "event-1" },
  },
  {
    id: "notif-2",
    type: "finance",
    title: "Dues update",
    body: "Q2 dues are now open for payment.",
    sentAt: new Date("2026-05-10T12:00:00+01:00"),
    target: { route: "my_ledger" },
  },
  {
    id: "notif-3",
    type: "vote",
    title: "Election opened",
    body: "The 2026 Executive Election is now active.",
    sentAt: new Date("2026-05-09T08:30:00+01:00"),
    target: { route: "election_ballot", electionId: "election-1" },
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    title: "Canon EOS 1300D Camera",
    price: 85000,
    description:
      "Used twice, excellent condition. Includes box, charger and 16GB card.",
    condition: "like_new",
    status: "available",
    imageURL: null,
    postedBy: "admin-1",
    postedByName: "Chukwuemeka Obi",
    contactInstruction: "WhatsApp the seller to arrange inspection and pickup.",
    createdAt: new Date("2026-05-01T10:00:00+01:00"),
    updatedAt: new Date("2026-05-01T10:00:00+01:00"),
  },
  {
    id: "listing-2",
    title: "Adjustable Standing Desk",
    price: 45000,
    description:
      "Height-adjustable desk, minor scratch on base. Lagos pickup only.",
    condition: "good",
    status: "sold",
    imageURL: null,
    postedBy: "admin-1",
    postedByName: "Chukwuemeka Obi",
    contactInstruction: "Sold items remain visible for price reference.",
    createdAt: new Date("2026-04-18T14:30:00+01:00"),
    updatedAt: new Date("2026-05-05T09:00:00+01:00"),
  },
];

export const mockLibraryDocuments: LibraryDocument[] = [
  {
    id: "doc-1",
    title: "Tiwani Constitution",
    description: "Current association constitution and governance reference.",
    category: "constitutional",
    type: "constitution",
    documentDate: new Date("2026-01-15"),
    uploadedAt: new Date("2026-01-20T10:00:00+01:00"),
    uploadedBy: "admin-1",
    uploadedByName: "Chukwuemeka Obi",
    status: "published",
    visibility: "all_members",
    fileName: "tiwani-constitution.pdf",
    fileURL: "https://example.com/tiwani-constitution.pdf",
    fileType: "pdf",
    fileSize: 542000,
  },
  {
    id: "doc-2",
    title: "Code of Conduct",
    description: "Member conduct standards for meetings, committees, and events.",
    category: "constitutional",
    type: "code_of_conduct",
    documentDate: new Date("2026-02-05"),
    uploadedAt: new Date("2026-02-06T12:30:00+01:00"),
    uploadedBy: "admin-1",
    uploadedByName: "Chukwuemeka Obi",
    status: "published",
    visibility: "all_members",
    fileName: "code-of-conduct.pdf",
    fileURL: "https://example.com/code-of-conduct.pdf",
    fileType: "pdf",
    fileSize: 214000,
  },
  {
    id: "doc-3",
    title: "April 2026 General Meeting Minutes",
    description: "Attendance, motions, finance notes, and action items from April.",
    category: "minutes_reports",
    type: "meeting_minutes",
    documentDate: new Date("2026-04-27"),
    uploadedAt: new Date("2026-04-29T09:15:00+01:00"),
    uploadedBy: "admin-1",
    uploadedByName: "Chukwuemeka Obi",
    status: "published",
    visibility: "all_members",
    fileName: "april-2026-minutes.pdf",
    fileURL: "https://example.com/april-2026-minutes.pdf",
    fileType: "pdf",
    fileSize: 318000,
  },
  {
    id: "doc-4",
    title: "Q1 2026 Finance Report",
    description: "Treasurer report covering collections, balances, and expenses.",
    category: "minutes_reports",
    type: "financial_report",
    documentDate: new Date("2026-03-31"),
    uploadedAt: new Date("2026-04-03T14:45:00+01:00"),
    uploadedBy: "admin-1",
    uploadedByName: "Chukwuemeka Obi",
    status: "draft",
    visibility: "admin_only",
    fileName: "q1-2026-finance-report.pdf",
    fileURL: null,
    fileType: "pdf",
    fileSize: 486000,
  },
];

export const delay = (ms = 150) =>
  new Promise<void>((resolve) => setTimeout(() => resolve(), ms));
